### ISSUE TITLE
Planner

### ISSUE THREAD

**Issue by attiliocaravelli** [nuvolaris/nuvolaris-testing#1]
Goal: Automatic Setup of the Dev Environment 

Programming language: Ansible
Toolkit: libvirt
PaaS: okd4
OS: Ubuntu/CentOS

This is an initial estimation of the release of the scripts (working 1hr per day):
1. set up a virtual network supporting the cluster (3 days)  --> libvirt
2. set up a virtual machine Ubuntu/CentOS based (7 days)  --> libvirt
3. set up of a cluster (4 days) --> libvirt
4. set up of the OKD4 (10 days)

**Comment by msciabarra** [comment]
noted
